version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/code/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web